#!/bin/busybox sh

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

cryptsetup --key-file /root/key luksOpen $(findfs UUID=c6d65ff0-36fa-4f63-8d93-d39ffb4043b7) ssd
mount -o ro,subvol=gentoo,ssd,noatime /dev/mapper/ssd /mnt/root

# Clean up.
umount /proc
umount /sys
umount /dev

# Boot the real thing.
exec switch_root /mnt/root /sbin/runit-init
